org.gradle.jvmargs=\
  --add-opens=java.base/java.lang=ALL-UNNAMED \
  --add-opens=java.base/java.util=ALL-UNNAMED \
  --add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
  --add-opens=java.base/java.io=ALL-UNNAMED \
  --add-opens=java.base/java.net=ALL-UNNAMED \
  --add-opens=java.base/sun.nio.ch=ALL-UNNAMED \
  --add-opens=java.base/java.nio=ALL-UNNAMED \
  --enable-native-access=ALL-UNNAMED \
  -XX:MaxMetaspaceSize=2G \
  -XX:ReservedCodeCacheSize=512m \
  -XX:+HeapDumpOnOutOfMemoryError \
  -XX:+UseParallelGC \
  -XX:+UseStringDeduplication \
  -Xmx6G \
  -Xms2G
# Gradle
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.workers.max=16
org.gradle.configureondemand=true
org.gradle.vfs.watch.verbose=false
# org.gradle.unsafe.configuration-cache=true
# org.gradle.unsafe.configuration-cache.problems=warn
# org.gradle.unsafe.configuration-cache.max-problems=5
org.gradle.build-cache=true
org.gradle.caching.debug=false
org.gradle.native-access=ENABLED
org.gradle.build-cache.local.enabled=true
# Android
android.r8.maxWorkers=8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.native.buildOutput=verbose
android.enableAppCompileTimeRClass=true
android.enableBuildConfigAsBytecode=true
android.experimental.androidTest.useUnifiedTestPlatform=true
android.experimental.testOptions.managedDevices.emulatorSnapshots.enabled=true
# Kotlin
kotlin.code.style=official
kotlin.incremental.useClasspathSnapshot=true
