org.gradle.jvmargs=\
  --add-opens=java.base/java.lang=ALL-UNNAMED \
  --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
  --add-opens=java.base/java.util=ALL-UNNAMED \
  --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  --add-opens=java.base/java.nio.charset=ALL-UNNAMED \
  --add-opens=java.base/java.net=ALL-UNNAMED \
  --add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
  --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
  --add-opens=java.xml/javax.xml.namespace=ALL-UNNAMED \
  --add-opens=java.base/java.time=ALL-UNNAMED \
  -XX:MaxMetaspaceSize=4G \
  -XX:ReservedCodeCacheSize=512m \
  -XX:+HeapDumpOnOutOfMemoryError \
  -XX:+UseParallelGC \
  -Xmx8G
org.gradle.caching=true
org.gradle.parallel=true
# org.gradle.configuration-cache=true

android.useAndroidX=true
android.enableAppCompileTimeRClass=true
android.enableBuildConfigAsBytecode=true
# Improve build performance by enabling R8 parallelism.
android.r8.maxWorkers=4

kotlin.code.style=official