org.gradle.jvmargs=\
  --add-opens=java.base/java.lang=ALL-UNNAMED \
  --add-opens=java.base/java.util=ALL-UNNAMED \
  --add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
  -XX:MaxMetaspaceSize=1G \
  -XX:ReservedCodeCacheSize=256m \
  -XX:+HeapDumpOnOutOfMemoryError \
  -XX:+UseParallelGC \
  -Xmx4G
# Gradle
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.workers.max=8
org.gradle.native-access=ENABLED
org.gradle.configureondemand=true
# Android
android.r8.maxWorkers=8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.native.buildOutput=verbose
android.enableAppCompileTimeRClass=true
android.enableBuildConfigAsBytecode=true
android.experimental.androidTest.useUnifiedTestPlatform=true
android.experimental.testOptions.managedDevices.emulatorSnapshots.enabled=true
# Kotlin
kotlin.code.style=official
kotlin.incremental.useClasspathSnapshot=true